### ISSUE TITLE
Comments in Carp start with a single semicolon

### ISSUE THREAD

**Issue by hellerve** [GrayJack/language-carp#1]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Comments in Carp start with a single semicolon. The current syntax file specifies two, which should be a somewhat simple fix!

Example:

```clojure
; hey, i’m a comment!
(def x @"and i am a definition")
```

### Steps to Reproduce

1. Type a comment with a single semicolon.

**Expected behavior:** A comment should be rendered.

**Actual behavior:* Syntax highlighting ignores it.

**Reproduces how often:** 100%

**Comment by GrayJack** [comment]
Fix :3
